#!/bin/sh
#  
#  mass_password_reset
#  
#  Copyright (C) 2013 - Luis Fernando Maldonado Arango
#  Copyright (C) 2013 - Summan S.A.S.
#  
#  mass_password_reset is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  mass_password_reset is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with checkWand.  If not, see <http://www.gnu.org/licenses/>.
#

LDAP_PATH="/usr/bin"
unset passdm
echo
PROMPT="Contraseña Directory Manager: "
while IFS= read -p "$PROMPT" -r -s -n 1 char; do
    if [[ $char == $'\0' ]]; then
        break
    fi
    PROMPT='*'
    passdm+="$char"
done
echo

echo -n "Nueva contraseña para usuarios: " ""
read passus


for userLdap in `$LDAP_PATH/ldapsearch -x -Z -LLL \
                -D "cn=directory manager" \
                -w "$passdm" \
                -b "dc=summan,dc=com" \
                "(objectclass=person)" dn | cut -d" " -f2`
do
echo -n "Cambiando contraseña de los usuarios..."
$LDAP_PATH/ldappasswd -x -Z -D "cn=directory manager" -w "$passdm" -s "$passus" "$userLdap"
echo " OK"
done

